# Generated by Django 3.1.2 on 2020-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
