# Generated by Django 3.1.2 on 2020-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201105_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phno',
            field=models.IntegerField(default=999999999),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default='Sastra', max_length=100),
        ),
    ]
